version: '3.7'

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: [ "/home/app/docker/backend/server-entrypoint.sh" ]
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    env_file:
      - ./app/core/.env
    networks:
      - network_custom
  nginx:
    container_name: nginx
    build: ./docker/nginx
    restart: always
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    ports:
      - 4001:80 #externe port of the serveur
    depends_on:
      - app
    logging:
      options:
        max-size: 10m
    networks:
      - network_custom
  redis:
    container_name: redis
    restart: always
    image: redis:7.0.5-alpine
    expose:
      - 6379
    networks:
      - network_custom
  deamons:
    container_name: celery-beat-deamons
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: [ "/home/app/docker/backend/daemon-entrypoint.sh" ]
    env_file:
      - ./app/core/.env
    depends_on:
      - app
      - redis
    volumes:
      - ./docker/supervisor/celery.conf:/etc/supervisor/conf.d/celery.conf
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    networks:
      - network_custom

networks:
  network_custom:
    name: telework_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 # to custom

volumes:
  static_volume: {}
  media_volume: {}
